// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Galeria → gallery*
 */
export interface GaleriaDocumentDataGalleryItem {
  /**
   * image title field in *Galeria → gallery*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: galeria.gallery[].image_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  image_title: prismic.KeyTextField;

  /**
   * image field in *Galeria → gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: galeria.gallery[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Content for Galeria documents
 */
interface GaleriaDocumentData {
  /**
   * gallery field in *Galeria*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: galeria.gallery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery: prismic.GroupField<Simplify<GaleriaDocumentDataGalleryItem>>;
}

/**
 * Galeria document from Prismic
 *
 * - **API ID**: `galeria`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GaleriaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<GaleriaDocumentData>,
    "galeria",
    Lang
  >;

type MengoNewsDocumentDataSlicesSlice = never;

/**
 * Content for Mengo News documents
 */
interface MengoNewsDocumentData {
  /**
   * Slice Zone field in *Mengo News*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: mengo_news.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<MengoNewsDocumentDataSlicesSlice> /**
   * Meta Title field in *Mengo News*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: mengo_news.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Mengo News*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: mengo_news.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Mengo News*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mengo_news.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Mengo News document from Prismic
 *
 * - **API ID**: `mengo_news`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MengoNewsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<MengoNewsDocumentData>,
    "mengo_news",
    Lang
  >;

/**
 * Content for Notícia documents
 */
interface NoticiaDocumentData {
  /**
   * title field in *Notícia*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: noticia.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *Notícia*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: noticia.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * date field in *Notícia*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: noticia.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * image field in *Notícia*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: noticia.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Notícia document from Prismic
 *
 * - **API ID**: `noticia`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NoticiaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NoticiaDocumentData>,
    "noticia",
    Lang
  >;

/**
 * Content for Resultado documents
 */
interface ResultadoDocumentData {
  /**
   * opponent field in *Resultado*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resultado.opponent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  opponent: prismic.KeyTextField;

  /**
   * result field in *Resultado*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resultado.result
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  result: prismic.KeyTextField;

  /**
   * date field in *Resultado*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: resultado.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * place field in *Resultado*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resultado.place
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  place: prismic.KeyTextField;
}

/**
 * Resultado document from Prismic
 *
 * - **API ID**: `resultado`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ResultadoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ResultadoDocumentData>,
    "resultado",
    Lang
  >;

export type AllDocumentTypes =
  | GaleriaDocument
  | MengoNewsDocument
  | NoticiaDocument
  | ResultadoDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      GaleriaDocument,
      GaleriaDocumentData,
      GaleriaDocumentDataGalleryItem,
      MengoNewsDocument,
      MengoNewsDocumentData,
      MengoNewsDocumentDataSlicesSlice,
      NoticiaDocument,
      NoticiaDocumentData,
      ResultadoDocument,
      ResultadoDocumentData,
      AllDocumentTypes,
    };
  }
}
