name: Update Flamengo News

on:
  schedule:
    - cron: '*/30 * * * *'  # Executa a cada 30 minutos
  workflow_dispatch:  # Permite execução manual

jobs:
  update-news:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run news update
        run: |
          curl -X GET ${{ secrets.VERCEL_URL }}/api/cron/update-news \
          -H "x-cron-secret: ${{ secrets.CRON_SECRET }}"
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          PRISMIC_ACCESS_TOKEN: ${{ secrets.PRISMIC_ACCESS_TOKEN }}
